# Generated by Django 2.2.3 on 2019-09-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0013_auto_20190806_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mesad',
            name='numero',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservad',
            name='mesad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReservaDis', to='reserva.MesaD'),
        ),
    ]
